apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: cargoflow-backend
spec:
  type: ClusterIP
  selector:
    app: cargoflow-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
